apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend-deployment
  namespace: bookstore-dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bookstore-backend

  template:
    metadata:
      labels:
        app: bookstore-backend

    spec:
      containers:
        - name: bookstore-backend

          image: jaydipaws/bookstore-backend:v1
          
          resources:
          
            requests:
              cpu: "100m"
              memory: "512Mi"


            limits:
              cpu: "500m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret

          ports:
            - containerPort: 5555

          readinessProbe:
          #kubernetes api calls inside container
            httpGet:
              path: /health

              port: 5555

            #wait for 10 second
            initialDelaySeconds: 10

            #check every 5 second period at every 5 second
            periodSeconds: 5

            #request time out
            timeoutSeconds: 2
            
            # failure 3 times mark not ready
            failureThreshold: 3
          
          livenessProbe: 

          #kubernetes api calls inside container
            httpGet:
              path: /health

              port: 5555 

            #wait for 10 second
            initialDelaySeconds: 30

            #check every 5 second period at every 5 second
            periodSeconds: 10

            #request time out
            timeoutSeconds: 2
            
            # failure 3 times mark not ready
            failureThreshold: 3

            

