api: apps/v1
kind: Deployment

metadata:
  name: bookstore-backend

spec:

  replicas: 2


  selector:
    matchlabel:
      app: backend


  template:

    metadata:
      labels:
        app: backend

    spec: 

      containers:
      - name: backend
        images: jaydipaws/bookstore-backend:v1
        
        imagePullPolicy: always

        ports:
        - containerPort: 5555 
          

