apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: bookstore-mongo-pvc
  namespace: bookstore-dev

spec:

  accessModes:

  - ReadWriteOnce


  storageClassName: bookstore-storage


  resources:

    requests:

      storage: 5Gi